package fiber

import (
	"fmt"
	"os"
	"strings"
)

const mainFileTemplate = `// This file is auto generated by polygo
package main

import (
	"os"

	"${moduleName}/cmd"
	_ "${moduleName}/docs"
)

// @title Fiber Example API
// @version 1.0
// @description This is a sample swagger for Fiber
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email fiber@swagger.io
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @BasePath /api
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
func main() {
	args := os.Args
	argsLength := len(args)
	if argsLength > 1 {
		cmd.Manager(args)
	} else {
		cmd.Serve()
	}
}
`

type FiberProject struct {
	ProjectName string
	ModuleName  string
	Directory   string
}

func (fp FiberProject) GenerateFiberProject() error {
	if err := fp.createMainFile(); err != nil {
		return err
	}

	if err := fp.createCMDManagerFile(); err != nil {
		return err
	}

	if err := fp.createServeFile(); err != nil {
		return err
	}

	if err := fp.createMigrateFile(); err != nil {
		return err
	}

	if err := fp.createENVGoFile(); err != nil {
		return err
	}

	if err := fp.createPostgresFile(); err != nil {
		return err
	}

	if err := fp.createModelFiles(); err != nil {
		return err
	}

	if err := fp.createRouteFiles(); err != nil {
		return err
	}

	if err := fp.createHandlerFiles(); err != nil {
		return err
	}

	if err := fp.createRepoFiles(); err != nil {
		return err
	}

	if err := fp.createUtilFiles(); err != nil {
		return err
	}

	return nil
}

func (fp FiberProject) createMainFile() error {
	mainFileBody := strings.ReplaceAll(mainFileTemplate, "${moduleName}", fp.ModuleName)

	// if err := os.Mkdir(fmt.Sprintf("%s", fp.Directory), 0755); err != nil {
	// 	return err
	// }

	mainFilePath := fmt.Sprintf("%s/main.go", fp.Directory)
	return os.WriteFile(mainFilePath, []byte(mainFileBody), 0644)
}
